"use client";

import Link from "next/link";
import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { demo, type Activation } from "@/lib/demo";
import { useMe, useSession } from "@/lib/queries";

export default function DemoOperator() {
  useSession();
  const { data: me } = useMe();
  const qc = useQueryClient();
  const [link, setLink] = useState("");
  const [selected, setSelected] = useState("");
  const [purchase, setPurchase] = useState<Activation["purchase_type"]>("subscription");
  const [revokeConfirmed, setRevokeConfirmed] = useState(false);
  const [copied, setCopied] = useState(false);
  const query = useQuery({ queryKey: ["demo-operator", me?.id], queryFn: demo.operator, enabled: !!me?.is_operator });
  const issued = (result: { pass_token: string }) => { setLink(`${window.location.origin}/demo#${result.pass_token}`); setCopied(false); void qc.invalidateQueries({ queryKey: ["demo-operator"] }); };
  const issue = useMutation({ mutationFn: demo.issue, onSuccess: issued });
  const activate = useMutation({ mutationFn: (data: Activation) => demo.activate(selected, data), onSuccess: issued });
  const revoke = useMutation({ mutationFn: () => demo.revoke(selected), onSuccess: () => { setRevokeConfirmed(false); void qc.invalidateQueries({ queryKey: ["demo-operator"] }); } });
  if (!me?.is_operator) return <div className="product-page"><h1>Demo operations</h1><p>This page is for configured KapkotiSolution operators.</p><Link href="/signin">Sign in</Link></div>;
  const data = query.data;
  const workspaces = data?.workspaces ?? [];
  const active = workspaces.filter(workspace => workspace.activated_at).length;
  const customers = workspaces.filter(workspace => workspace.access.mode === "customer").length;
  return <div className="product-page">
    <header className="page-heading"><div><p className="eyebrow">KAPKOTISOLUTION</p><h1>Demo operations</h1><p>Issue private trials and record verified product access.</p></div><button className="btn" disabled={query.isFetching} onClick={() => void query.refetch()}>Refresh</button></header>
    {(query.error || issue.error || activate.error || revoke.error) && <p role="alert" className="notice error-text">{(query.error || issue.error || activate.error || revoke.error)?.message}</p>}
    <div className="metric-grid"><article><span>Passes issued</span><strong>{workspaces.length}</strong><small>Private workspaces</small></article><article><span>Activated</span><strong>{active}</strong><small>{workspaces.length ? `${Math.round(active / workspaces.length * 100)}% of issued passes` : "No passes yet"}</small></article><article><span>Product customers</span><strong>{customers}</strong><small>Manually verified purchases</small></article><article><span>Surveys created</span><strong>{workspaces.reduce((sum, row) => sum + row.access.surveys_created, 0)}</strong><small>Lifetime, including deleted surveys</small></article></div>
    {data && <section className="product-card"><h2>Shared demo AI budget</h2><p>UTC month beginning {data.month}. Customer workspaces are outside this demo cap.</p><div className="budget-meter"><meter value={data.charged_or_reserved_usd} min={0} max={data.budget_usd || 1} /><strong>${data.charged_or_reserved_usd.toFixed(4)} / ${data.budget_usd.toFixed(2)}</strong></div><p>${data.known_spend_usd.toFixed(4)} priced from reported usage · {data.uncertain_attempts} attempts with cost reserved or unknown · {data.failed_attempts} failed out of {data.attempts} attempts.</p><p className="muted">Reservations are kept if a request fails or usage is missing. Costs use configured provider rates. New paid demo calls stop when there is no room for their reservation.</p></section>}
    {link && <section className="product-card"><h2>New private access link</h2><p>Copy this link and deliver it privately to the verified contact. It is shown only in this session.</p><label htmlFor="issued-link">Private workspace link</label><textarea id="issued-link" value={link} readOnly rows={3} onFocus={event => event.currentTarget.select()} /><button className="btn btn-primary" onClick={async () => { try { await navigator.clipboard.writeText(link); setCopied(true); } catch { setCopied(false); } }}>{copied ? "Copied" : "Copy private link"}</button></section>}
    <div className="operator-forms"><section className="product-card"><h2>Issue a 14-day demo</h2><p>Three lifetime surveys, ten questions per survey and twenty respondent sessions per survey.</p><form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); issue.mutate({ name: String(form.get("name")), company: String(form.get("company")), email: String(form.get("email")) }); }}><label htmlFor="contact-name">Contact name</label><input id="contact-name" name="name" maxLength={200} required /><label htmlFor="contact-company">Company</label><input id="contact-company" name="company" maxLength={200} required /><label htmlFor="contact-email">Email</label><input id="contact-email" name="email" type="email" maxLength={320} required /><button className="btn btn-primary" disabled={issue.isPending}>{issue.isPending ? "Issuing…" : "Issue private pass"}</button></form></section>
    <section className="product-card"><h2>Activate a product customer</h2><p>Verify the purchase outside Elenchus first. Choose the company and agree its monthly response-session allowance.</p><form onSubmit={event => { event.preventDefault(); const form = new FormData(event.currentTarget); const until = String(form.get("until") ?? ""); activate.mutate({ product: String(form.get("product")), purchase_type: purchase, valid_until: purchase === "subscription" ? new Date(until).toISOString() : null, monthly_response_allowance: Number(form.get("allowance")), purchase_verified: true }); }}><label htmlFor="activate-workspace">Company workspace</label><select id="activate-workspace" required value={selected} onChange={event => { setSelected(event.target.value); setRevokeConfirmed(false); }}><option value="">Choose a company</option>{workspaces.map(row => <option key={row.workspace_id} value={row.workspace_id}>{row.company} ({row.email})</option>)}</select><label htmlFor="purchased-product">Purchased KapkotiSolution product</label><input id="purchased-product" name="product" required maxLength={200} placeholder="Sedno, FloorMind, or another product" /><label htmlFor="purchase-type">Purchase type</label><select id="purchase-type" value={purchase} onChange={event => setPurchase(event.target.value === "one_time" ? "one_time" : "subscription")}><option value="subscription">Active subscription</option><option value="one_time">One-time purchase</option></select>{purchase === "subscription" && <><label htmlFor="paid-until">Paid through, local date and time</label><input id="paid-until" name="until" type="datetime-local" required /></>}<label htmlFor="response-allowance">Agreed respondent sessions per UTC month</label><input id="response-allowance" name="allowance" type="number" min={1} max={100000} required /><label className="check-label"><input type="checkbox" required />I verified the purchase and agreed this allowance with the customer.</label><button className="btn btn-primary" disabled={activate.isPending}>{activate.isPending ? "Activating…" : "Activate and issue a new access link"}</button></form><details><summary>Revoke the selected workspace</summary><p>Stops access immediately, including existing sessions. Stored responses are retained.</p><label className="check-label"><input type="checkbox" checked={revokeConfirmed} onChange={event => setRevokeConfirmed(event.target.checked)} />Revoke this company&apos;s access.</label><button className="btn" disabled={!selected || !revokeConfirmed || revoke.isPending} onClick={() => revoke.mutate()}>Revoke access</button></details></section></div>
    <section className="product-card"><h2>Workspace directory</h2><div className="table-scroll"><table><thead><tr><th>Company</th><th>Contact</th><th>Access</th><th>Created surveys</th><th>Expiry</th></tr></thead><tbody>{workspaces.map(row => <tr key={row.workspace_id}><td>{row.company}</td><td>{row.email}</td><td>{row.access.mode} · {row.access.active ? "active" : "inactive"}</td><td>{row.access.surveys_created}{row.access.survey_limit !== null ? ` / ${row.access.survey_limit}` : ""}</td><td>{row.access.expires_at ? new Date(row.access.expires_at).toLocaleString() : "No expiry"}</td></tr>)}</tbody></table></div></section>
  </div>;
}
